### Create Department
POST http://localhost:8080/api/departments
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3ZGU1NDc3LWNjZGItNDYxYy1iNTIxLTlmYjBlNzM2MGU5ZSIsInVzZXJuYW1lIjoic3VrZW5kYSIsInJvbGUiOiJBZG1pbiIsImV4cCI6MTYxMDc4NDk5MH0.KKwLnHq3oNRxZamq13k9ASIYfPA1EEKp7Ssxp2yeJ9E

{
  "name": "Marketing",
  "description": "Marketing desc"
}

### Find Department
GET http://localhost:8080/api/departments
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3ZGU1NDc3LWNjZGItNDYxYy1iNTIxLTlmYjBlNzM2MGU5ZSIsInVzZXJuYW1lIjoic3VrZW5kYSIsInJvbGUiOiJBZG1pbiIsImV4cCI6MTYxMDc4NDk5MH0.KKwLnHq3oNRxZamq13k9ASIYfPA1EEKp7Ssxp2yeJ9E